/*1*/
UPDATE DEBITOS a 
SET SITUACAO_DEBITO = 'atrasado'
WHERE DATAVENCIMENTO < CURRENT_DATE
AND SITUACAO_DEBITO NOT IN ('Negociado', 'Pago');
 
SELECT * FROM DEBITOS d 
WHERE DATAVENCIMENTO < CURRENT_DATE
AND  situacao_debito NOT IN ('negociado', 'pago');
 
/*2*/
UPDATE DEBITOS 
SET SITUACAO_DEBITO = 'Pedente'
WHERE DATAVENCIMENTO > CURRENT_DATE
AND SITUACAO_DEBITO NOT IN ('pago');
 
SELECT * FROM DEBITOS d 
SET DATAVENCIMENTO = CURRENT_DATE
AND SITUACAO_DEBITO NOT IN ('pago');
 
/*3*/
UPDATE DEBITOS d 
SET DATAVENCIMENTO = DATEADD(-5 YEAR TO DATAVENCIMENTO) 
where SITUACAO_DEBITO IN ('Negociado');
 
SELECT * FROM DEBITOS d
WHERE SITUACAO_DEBITO IN ('Negociado');
 
/*4*/
SELECT p.nome, p.email, p.telefone,
FROM pessoa p
 
/*5*/
SELECT * FROM produto p
WHERE PRECO_UNITARIO > 100
 
/*6*/
SELECT * FROM VENDA v 
WHERE v.DATA_VENDA BETWEEN '2014-10-22' AND '2022-05-04'
 
/*7*/
SELECT p.nome, p.data_nascimento, (CURRENT_DATE - p.data_nascimento) FROM FORNECEDOR f 
LEFT JOIN PESSOA p ON p.ID_PESSOA = f.ID_FORNECEDOR 
WHERE f.ID_FORNECEDOR IN (SELECT ID_FORNECEDOR FROM PRODUTO p2 WHERE quantidade_estoque IS NULL)
 
 /*8*/
SELECT p.NOME, p.EMAIL, p.TELEFONE, d.DATAVENCIMENTO, d.SITUACAO_DEBITO
FROM cliente c
INNER JOIN pessoa p ON c.ID_PESSOA = p.ID_PESSOA
LEFT JOIN DEBITOS d ON c.ID_CLIENTE = d.ID_CLIENTE
ORDER BY p.NOME;
/*9*/

/*11*/
UPDATE  PRODUTO p
SET PRECO_UNITARIO = PRECO_UNITARIO + (PRECO_UNITARIO * 10)
WHERE p.QUANTIDADE_ESTOQUE < 10

 
/*13*/
UPDATE DEBITOS D
SET SITUACAO_DEBITO = 'pago'
WHERE D.SITUACAO_DEBITO NOT IN ('atrasado')
 
SELECT *FROM DEBITOS d 
WHERE d.SITUACAO_DEBITO IN ('atrasado')
 
SELECT * FROM PAGAMENTO p, DEBITOS d 
WHERE p.ID_DEBITO = d.ID_DEBITO
 
/*15*/
SELECT *
FROM VENDA
WHERE DATA_VENDA BETWEEN '2023-12-01' AND '2024-01-31'

/*16*/
SELECT *
FROM PRODUTO
WHERE QUANTIDADE_ESTOQUE BETWEEN 5 AND 20;

/*17*/
SELECT *
FROM PESSOA
WHERE NOME LIKE 'A%';

 /*18*/
SELECT * 

/*19*/
SELECT p.NOME AS Produto, v.DATA_VENDA, c.ID_PESSOA AS Cliente
FROM VENDA v
INNER JOIN CLIENTE c ON v.ID_PESSOA = c.ID_PESSOA
INNER JOIN PRODUTO p ON v.ID_VENDA = p.ID_PRODUTO
WHERE c.ID_PESSOA IN ('Ana Luiza', 'Gabriela Ferreira');